### ISSUE TITLE
Spring Guide - Building a Gateway - https://spring.io/guides/gs/gateway/

### ISSUE THREAD

**Issue by girishyt** [spring-guides/getting-started-guides#159] opened 2023-12-11 12:55 UTC
I followed this guide and initialized the project from start.spring.io.
I'm trying to create a new route using Java RouteLocator API but i can't find this class in the jar "spring-cloud-starter-gateway-mvc".
Upon doing some research i found out that this class is part of "spring-cloud-starter-gateway" jar which is for a Reactive Cloud Gateway.
The guide title and description says the example given is for non reactive. Please check.

Thanks

**Comment by robertmcnees** [comment] 2024-05-09 14:33
Hi @girishyt. You are correct that the gateway guide had an issue with how we resolved the gateway dependency. This should be solved by the recently merged PRs in the [gs-gateway](https://github.com/spring-guides/gs-gateway) project. As a reminder, please use the specific guide repositories when possible to open issues.  Additional context for the root of the problem is located in those PRs.

This should now be fixed with the 2 recent PRs:

- [Update Dependencies](https://github.com/spring-guides/gs-gateway/pull/23)
- [Update README](https://github.com/spring-guides/gs-gateway/pull/22)

I'll close the issue as resolved. If you try and are still having difficulties, please submit a follow up issue in the gs-gateway repository and we can have another look.

**Closed by robertmcnees** 2024-05-09 14:33 UTC
