### ISSUE TITLE
Getting Started Consuming REST AngularJS not pulling in data correctly

### ISSUE THREAD

**Issue by ericop** [spring-guides/getting-started-guides#18] opened 2015-10-20 14:45 UTC
So http://rest-service.guides.spring.io/greeting is up and running
```
{
   id: 415,
   content: "Hello, World!"
}
```

but running`gs-consuming-rest-angularjs-complete` (obtained thru STS 3.7.1 File > New > Import Spring Getting Started Content)  thru the app.groovy  (with Spring CLI v1.2.7.RELEASE) doesn't pull in dynamic content to be rendered.

**Expected when visiting http://localhost:8080/**
The ID is 415

The content is Hello, World!

**Actual**

The ID is

The content is

**Comment by dsyer** [comment] 2015-10-20 14:59
I don't know who is maintaining that service but it isn't serving CORS headers ( @gregturn maybe?). Look in your Javascupt console for errors like this:

```
XMLHttpRequest cannot load http://rest-service.guides.spring.io/greeting. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

**Comment by ericop** [comment] 2015-10-20 15:02
Spot on @dsyer ! Hopefully the CORS stuff can get patched up and this demo will be operational once again.

**Comment by robertolopezlopez** [comment] 2016-02-05 08:52
It's happening to me as well. On Firefox it's not logging anything, but on chromium I have got the following:
`XMLHttpRequest cannot load http://rest-service.guides.spring.io/greeting. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

**Comment by gregturn** [comment] 2016-02-05 12:39
All of the JS guides have this CORS issue. I haven't figured out how to get the policy
Working properly for the CF-hosted backend service.

**Comment by dsyer** [comment] 2016-02-05 12:45
Where is the source code?

**Comment by robertolopezlopez** [comment] 2016-02-05 12:48
here https://github.com/spring-guides/gs-consuming-rest-angularjs/tree/master/complete

**Comment by dsyer** [comment] 2016-02-05 12:51
Thanks but that's the guide, not the service it consumes.

**Comment by dsyer** [comment] 2016-05-07 09:50
Works for me now (I think this is a duplicate of https://github.com/spring-guides/gs-consuming-rest-angularjs/issues/2)

**Closed by dsyer** 2016-05-07 09:50 UTC
