### ISSUE TITLE
Apache Kafka Guide for Spring Boot

### ISSUE THREAD

**Issue by MihSawant** [spring-guides/getting-started-guides#152] opened 2022-11-03 18:29 UTC
I would like to contribute for Apache Kafka messaging service for Spring Boot

**Comment by MihSawant** [comment] 2022-11-03 18:30
It would be a sample application and explain the broker, producer, consumer and topic

**Comment by kunalvarpe** [comment] 2023-11-18 13:10
@MihSawant Are you working on this? I would also love to contribute here, let me know we we can do it toghether.

**Comment by robertmcnees** [comment] 2024-07-10 13:56
Closing as a duplicate of #72

**Closed by robertmcnees** 2024-07-10 13:56 UTC
Labels: duplicate, new guide request
